# Generated by Django 4.1.5 on 2023-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('start_datetime', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'logs',
                'managed': True,
            },
        ),
    ]
