# Generated by Django 4.1.5 on 2023-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='source',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
