# Generated by Django 4.1.5 on 2023-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_logs_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='callback_url',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
