# Generated by Django 4.1.5 on 2023-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0003_logs_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='queueId',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
