# Generated by Django 4.1.5 on 2023-02-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_logs_queueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='queueId',
            field=models.CharField(max_length=2000),
        ),
    ]
