# Generated by Django 4.1.6 on 2023-03-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_alter_logs_queueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
