# Generated by Django 4.1.6 on 2023-03-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0006_alter_logs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
