# Generated by Django 4.1.6 on 2023-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_logs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='email',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
